name: "Run Lint, Build, Tests, and Coverage Collection"
description: "Run the required actions"
runs:
  using: "composite"
  steps:
    - name: Run Format Check
      run: npx nx affected --base development -t format:check
      shell: bash
    - name: Run Lint Check
      run: npx nx affected --base development -t lint:check
      shell: bash
    - name: Run Test Check
      run: npx nx affected --base development -t test
      shell: bash
    - name: Build Project
      run: npx nx affected --base development -t build
      shell: bash
    # - name: Run Integration Tests
    #   run: pnpm e2e -- --skip-nx-cache
    #   shell: bash
    #   env:
    #     NX_CLOUD_DISTRIBUTED_EXECUTION: false
    # - name: Stop Nx Cloud Agents
    #   run: pnpx -y nx-cloud stop-all-agents
    #   shell: bash
    # - name: Debug Coverage
    #   run: cat coverage/lcov.info
    #   shell: bash
    # - name: Upload Coverage
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: coverage
    #     path: coverage/lcov.info
