name: CI

on:
  push:
    branches:
      - main
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write

env:
  PRIMARY_NODE_VERSION: 20

jobs:
  tag-prerelease:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

      - name: Build
        uses: ./.github/actions/prepare-build

      - name: Tag branch if all jobs succeed
        uses: nrwl/nx-tag-successful-ci-run@v1

      - run: git config --global user.email "release-bot<>"
      - run: git config --global user.name "guesant/unispec release bot"

      - run: npx nx release --specifier minor --skip-publish
        if: ${{  github.ref == 'refs/heads/main' }}

      - run: npx nx release --specifier preminor --skip-publish
        if: ${{  github.ref == 'refs/heads/development' }}

      - run: git push --follow-tags
