name: CI

on:
  push:
    branches:
      - main
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write

env:
  PRIMARY_NODE_VERSION: 20

jobs:
  tag:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

      - name: Build
        uses: ./.github/actions/prepare-build

      - name: Tag branch if all jobs succeed
        uses: nrwl/nx-tag-successful-ci-run@v1

      - run: git config user.name 'github-actions[bot]'
      - run: git config user.email 'github-actions[bot]@users.noreply.github.com'

      - run: npx nx release --specifier ${SPECIFIER} --skip-publish
        if: ${{ github.ref == 'refs/heads/development' }}
        env:
          SPECIFIER: ${{ github.ref == 'refs/heads/development' && 'prerelease' || 'release' }}

      - run: git push --follow-tags

      - run: npx nx release publish --tag ${TAG} --verbose
        env:
          TAG: ${{ github.ref == 'refs/heads/development' && 'next' || 'latest' }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
