name: "Pull Request: Quality Check"

on:
  pull_request:
    types:
      - opened
    branches:
      - "main"
      - "development"

permissions:
  actions: read
  contents: read

env:
  PRIMARY_NODE_VERSION: 20

jobs:
  install:
    name: Checkout and Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

  quality-check:
    name: Code Quality Check
    needs: [install]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ matrix.node-version }}
      - name: Quality Check
        uses: ./.github/actions/quality-check
