name: Publish Pre-Release Package

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  PRIMARY_NODE_VERSION: 20

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      actions: read
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

      - name: Build
        uses: ./.github/actions/prepare-build

      - name: Configure NPM token
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      - run: npx nx release publish --tag next --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
